// <auto-generated />
namespace survey_demo_api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class addcolumnstodefault : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcolumnstodefault));
        
        string IMigrationMetadata.Id
        {
            get { return "202005121331075_addcolumnstodefault"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
